# --------------------------------------------------
# Checkov configuration (generic & CI-friendly)
# --------------------------------------------------

# Frameworks to scan
framework:
  - terraform
  - dockerfile
  - secrets

# Output behavior
output:
  - cli
  - junitxml

# CI behavior
soft-fail: true
quiet: false

# Skip specific checks that are intentionally not enforced
skip-check:
  - CKV_AWS_18   # S3 Bucket access logging
  - CKV_AWS_21   # S3 Bucket MFA delete

# Paths to exclude from scanning
skip-path:
  - .git
  - .terraform
  - node_modules
  - reports

# NOTE:
# - Do NOT define custom severity mappings here
# - Do NOT use skip-file (not supported by Checkov)
# - .tfvars files are ignored by Checkov automatically
